spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx:3306/test
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis别名包的位置，进行扫描
mybatis:
  type-aliases-package: com.shendu.springbootshiro.bean
  mapperLocations: classpath:mapper/*.xml